version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: fintrackdb
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fintrack"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  pgdata:
